// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using QueryExample.EntityFramework;
using System;

namespace QueryExample.Migrations
{
    [DbContext(typeof(QueryExampleContext))]
    [Migration("20180222183716_CreateDBStructure")]
    partial class CreateDBStructure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("QueryExample.Entities.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DislikeCount");

                    b.Property<int>("LikeCount");

                    b.Property<int>("QuestId");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("QueryExample.Entities.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Answer1Text")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Answer2Text")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Answer3Text")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Answer4Text")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("QueryExample.Entities.QuestPass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CompetitionId");

                    b.Property<DateTimeOffset?>("CreatedAt");

                    b.Property<decimal>("PointsScored");

                    b.Property<int>("QuestId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("QuestId");

                    b.HasIndex("UserId");

                    b.ToTable("QuestPasses");
                });

            modelBuilder.Entity("QueryExample.Entities.QuestTag", b =>
                {
                    b.Property<int>("QuestId");

                    b.Property<int>("TagId");

                    b.HasKey("QuestId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("QuestTags");
                });

            modelBuilder.Entity("QueryExample.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("QueryExample.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .HasMaxLength(128);

                    b.Property<string>("Fullname")
                        .HasMaxLength(256);

                    b.Property<bool>("IsEmailConfirmed");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QueryExample.Entities.UserFriend", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("FriendId");

                    b.HasKey("UserId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("UserFriends");
                });

            modelBuilder.Entity("QueryExample.Entities.Competition", b =>
                {
                    b.HasOne("QueryExample.Entities.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QueryExample.Entities.Quest", b =>
                {
                    b.HasOne("QueryExample.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QueryExample.Entities.QuestPass", b =>
                {
                    b.HasOne("QueryExample.Entities.Competition", "Competition")
                        .WithMany("Passes")
                        .HasForeignKey("CompetitionId");

                    b.HasOne("QueryExample.Entities.Quest", "Quest")
                        .WithMany("Passes")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QueryExample.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QueryExample.Entities.QuestTag", b =>
                {
                    b.HasOne("QueryExample.Entities.Quest", "Quest")
                        .WithMany("QuestTags")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QueryExample.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QueryExample.Entities.UserFriend", b =>
                {
                    b.HasOne("QueryExample.Entities.User", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QueryExample.Entities.User", "User")
                        .WithMany("UserFriends")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
